services:
  - type: web
    name: prishaa-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
<<<<<<< HEAD
  healthCheckPath: /api/health
=======
>>>>>>> 12e577b83e451d44c97e8e9add6c7afd6aedfce2
